
// This file was auto-generated by 'include/TOKEN/generate_c.py'

const char *global_token_name_table[] = {
    "none",                               // 0x00000000
    "word",                               // 0x00000001
    "string",                             // 0x00000002
    "cstring",                            // 0x00000003
    "add",                                // 0x00000004
    "subtract",                           // 0x00000005
    "multiply",                           // 0x00000006
    "divide",                             // 0x00000007
    "assign",                             // 0x00000008
    "equals",                             // 0x00000009
    "notequals",                          // 0x0000000A
    "lessthan",                           // 0x0000000B
    "greaterthan",                        // 0x0000000C
    "lessthaneq",                         // 0x0000000D
    "greaterthaneq",                      // 0x0000000E
    "not",                                // 0x0000000F
    "open",                               // 0x00000010
    "close",                              // 0x00000011
    "begin",                              // 0x00000012
    "end",                                // 0x00000013
    "newline",                            // 0x00000014
    "byte",                               // 0x00000015
    "ubyte",                              // 0x00000016
    "short",                              // 0x00000017
    "ushort",                             // 0x00000018
    "int",                                // 0x00000019
    "uint",                               // 0x0000001A
    "long",                               // 0x0000001B
    "ulong",                              // 0x0000001C
    "usize",                              // 0x0000001D
    "float",                              // 0x0000001E
    "double",                             // 0x0000001F
    "member",                             // 0x00000020
    "address",                            // 0x00000021
    "next",                               // 0x00000022
    "bracket open",                       // 0x00000023
    "bracket close",                      // 0x00000024
    "modulus",                            // 0x00000025
    "generic int",                        // 0x00000026
    "generic float",                      // 0x00000027
    "add assign",                         // 0x00000028
    "subtract assign",                    // 0x00000029
    "multiply assign",                    // 0x0000002A
    "divide assign",                      // 0x0000002B
    "modulus assign",                     // 0x0000002C
    "bitwise and assign",                 // 0x0000002D
    "bitwise or assign",                  // 0x0000002E
    "bitwise xor assign",                 // 0x0000002F
    "bitwise left shift assign",          // 0x00000030
    "bitwise right shift assign",         // 0x00000031
    "bitwise logical left shift assign",  // 0x00000032
    "bitwise logical right shift assign", // 0x00000033
    "ellipsis",                           // 0x00000034
    "uber and",                           // 0x00000035
    "uber or",                            // 0x00000036
    "terminate join",                     // 0x00000037
    "colon",                              // 0x00000038
    "bitwise or",                         // 0x00000039
    "bitwise xor",                        // 0x0000003A
    "bitwise left shift",                 // 0x0000003B
    "bitwise right shift",                // 0x0000003C
    "bit complement",                     // 0x0000003D
    "bitwise logical left shift",         // 0x0000003E
    "bitwise logical right shift",        // 0x0000003F
    "associate",                          // 0x00000040
    "meta",                               // 0x00000041
    "polymorph",                          // 0x00000042
    "maybe",                              // 0x00000043
    "increment",                          // 0x00000044
    "decrement",                          // 0x00000045
    "toggle",                             // 0x00000046
    "strong arrow",                       // 0x00000047
    "range",                              // 0x00000048
    "gives",                              // 0x00000049
    "polycount",                          // 0x0000004A
    "POD keyword",                        // 0x0000004B
    "alias keyword",                      // 0x0000004C
    "alignof keyword",                    // 0x0000004D
    "and keyword",                        // 0x0000004E
    "as keyword",                         // 0x0000004F
    "assert keyword",                     // 0x00000050
    "at keyword",                         // 0x00000051
    "break keyword",                      // 0x00000052
    "case keyword",                       // 0x00000053
    "cast keyword",                       // 0x00000054
    "class keyword",                      // 0x00000055
    "const keyword",                      // 0x00000056
    "constructor keyword",                // 0x00000057
    "continue keyword",                   // 0x00000058
    "def keyword",                        // 0x00000059
    "default keyword",                    // 0x0000005A
    "defer keyword",                      // 0x0000005B
    "define keyword",                     // 0x0000005C
    "delete keyword",                     // 0x0000005D
    "each keyword",                       // 0x0000005E
    "else keyword",                       // 0x0000005F
    "embed keyword",                      // 0x00000060
    "enum keyword",                       // 0x00000061
    "exhaustive keyword",                 // 0x00000062
    "extends keyword",                    // 0x00000063
    "external keyword",                   // 0x00000064
    "fallthrough keyword",                // 0x00000065
    "false keyword",                      // 0x00000066
    "for keyword",                        // 0x00000067
    "foreign keyword",                    // 0x00000068
    "func keyword",                       // 0x00000069
    "funcptr keyword",                    // 0x0000006A
    "global keyword",                     // 0x0000006B
    "if keyword",                         // 0x0000006C
    "implicit keyword",                   // 0x0000006D
    "import keyword",                     // 0x0000006E
    "in keyword",                         // 0x0000006F
    "inout keyword",                      // 0x00000070
    "llvm_asm keyword",                   // 0x00000071
    "namespace keyword",                  // 0x00000072
    "new keyword",                        // 0x00000073
    "null keyword",                       // 0x00000074
    "or keyword",                         // 0x00000075
    "out keyword",                        // 0x00000076
    "override keyword",                   // 0x00000077
    "packed keyword",                     // 0x00000078
    "pragma keyword",                     // 0x00000079
    "private keyword",                    // 0x0000007A
    "public keyword",                     // 0x0000007B
    "record keyword",                     // 0x0000007C
    "repeat keyword",                     // 0x0000007D
    "return keyword",                     // 0x0000007E
    "sizeof keyword",                     // 0x0000007F
    "static keyword",                     // 0x00000080
    "stdcall keyword",                    // 0x00000081
    "struct keyword",                     // 0x00000082
    "switch keyword",                     // 0x00000083
    "thread_local keyword",               // 0x00000084
    "true keyword",                       // 0x00000085
    "typeinfo keyword",                   // 0x00000086
    "typenameof keyword",                 // 0x00000087
    "undef keyword",                      // 0x00000088
    "union keyword",                      // 0x00000089
    "unless keyword",                     // 0x0000008A
    "until keyword",                      // 0x0000008B
    "using keyword",                      // 0x0000008C
    "va_arg keyword",                     // 0x0000008D
    "va_copy keyword",                    // 0x0000008E
    "va_end keyword",                     // 0x0000008F
    "va_start keyword",                   // 0x00000090
    "verbatim keyword",                   // 0x00000091
    "virtual keyword",                    // 0x00000092
    "while keyword",                      // 0x00000093
};

const char global_token_extra_format_table[] = "abcbaaaaaaaaaaaaaaaaadddddddddddaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";

const char *global_token_keywords_list[] = {
    "POD",
    "alias",
    "alignof",
    "and",
    "as",
    "assert",
    "at",
    "break",
    "case",
    "cast",
    "class",
    "const",
    "constructor",
    "continue",
    "def",
    "default",
    "defer",
    "define",
    "delete",
    "each",
    "else",
    "embed",
    "enum",
    "exhaustive",
    "extends",
    "external",
    "fallthrough",
    "false",
    "for",
    "foreign",
    "func",
    "funcptr",
    "global",
    "if",
    "implicit",
    "import",
    "in",
    "inout",
    "llvm_asm",
    "namespace",
    "new",
    "null",
    "or",
    "out",
    "override",
    "packed",
    "pragma",
    "private",
    "public",
    "record",
    "repeat",
    "return",
    "sizeof",
    "static",
    "stdcall",
    "struct",
    "switch",
    "thread_local",
    "true",
    "typeinfo",
    "typenameof",
    "undef",
    "union",
    "unless",
    "until",
    "using",
    "va_arg",
    "va_copy",
    "va_end",
    "va_start",
    "verbatim",
    "virtual",
    "while",
};

unsigned long long global_token_keywords_list_length = 73;
